### ISSUE TITLE
please modify datepicker for buddhist year

### ISSUE THREAD

**Issue by thamwebsite** [mymth/vanillajs-datepicker#151] opened 2023-06-14 06:57 UTC
how to modify vanillajs-datepicker to show buddhist year

Year : 2023
Buddhist Year : 2023+543 = 2567

I cann't modify to support buddhist year (T_T)

**Comment by mymth** [comment] 2023-06-21 04:38
Duplicate of #43

**Closed by mymth** 2023-06-21 04:38 UTC
