### ISSUE TITLE
Plans for bootstrap@5.3 support ?

### ISSUE THREAD

**Issue by martinbarilik** [mymth/vanillajs-datepicker#169] opened 2023-10-24 10:03 UTC
Any plans ?

![image](https://github.com/mymth/vanillajs-datepicker/assets/58255651/ed2922dc-4a4f-410e-a60d-69056cb5cef9)

I am unable to upgrade to bootstrap without having vanilla datepicker being compatibile :) 

Cheers

**Comment by mymth** [comment] 2023-10-28 02:35
Please see #146, https://github.com/mymth/vanillajs-datepicker/blob/master/CHANGELOG.md#133
Which version are you using?

**Comment by mymth** [comment] 2023-11-04 18:55
Duplicate of #146

**Closed by mymth** 2023-11-04 18:55 UTC
