### ISSUE TITLE
Support TypeScript

### ISSUE THREAD

**Issue by kurneo** [mymth/vanillajs-datepicker#120] opened 2022-08-14 02:11 UTC
Can you add support for TypeScript. thank in advance

**Comment by rougin** [comment] 2022-11-23 10:05
Hello! As I checked now, the library is currently supporting Typescript in this opened issue: https://github.com/mymth/vanillajs-datepicker/issues/59

**Comment by mymth** [comment] 2023-02-12 23:51
Duplicate of #59

**Closed by mymth** 2023-02-12 23:51 UTC
